name: my_dl
channels:
  - conda-forge
  - pytorch
  - defaults
dependencies:
  - python=3.12
  - pip
  - cupy
  - numpy=1.26.4
  - jupyter
  - jupyterlab==4.5.5
  - jupyterlab-language-pack-zh-cn==4.5.post1
  - notebook
  - matplotlib
  - scikit-learn
  - tensorboard
  - torch==2.5.1
  - torchaudio==2.5.1
  - torchvision==0.20.1
  - lightning
  - huggingface-hub
  - transformers
  - datasets
  - accelerate
  - evaluate
  - gradio